//! OpenCode Go / Zen style code generation and sandboxed execution.
//!
//! This module provides a high-quality *local* code generator that produces
//! real, runnable Python scaffolds tailored to the task description.  It is
//! designed to be replaced by a live OpenCode Go/Zen HTTP endpoint (or any
//! other model) simply by implementing a different backend behind the same
//! public API.  The sandbox is mandatory – there is no unsafe fallback.

use std::path::PathBuf;
use std::process::Command;

use tokio::fs;
use tracing::info;

use crate::error::ConciergeError;

/// Which code-generation style to use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodeAgentMode {
    /// Fast, lightweight generation (OpenCode Go style)
    Go,
    /// Deeper reasoning / ML-aware generation (OpenCode Zen style)
    Zen,
}

/// Generates and executes Python code under the Concierge sandbox.
pub struct CodeAgent {
    mode: CodeAgentMode,
    sandbox_script: PathBuf,
}

impl CodeAgent {
    /// Create a new code agent.  The sandbox script is resolved from:
    /// 1. `CONCIERGE_SANDBOX` environment variable
    /// 2. relative paths next to the binary / crate
    /// 3. the absolute path used in the OmniForge monorepo
    pub fn new(mode: CodeAgentMode) -> Self {
        let sandbox_script = std::env::var("CONCIERGE_SANDBOX")
            .map(PathBuf::from)
            .unwrap_or_else(|_| {
                let candidates = [
                    PathBuf::from("concierge-python-sandbox/sandbox.py"),
                    PathBuf::from("../concierge-python-sandbox/sandbox.py"),
                    PathBuf::from("/home/workdir/artifacts/concierge/concierge-python-sandbox/sandbox.py"),
                ];
                candidates
                    .into_iter()
                    .find(|p| p.exists())
                    .unwrap_or_else(|| PathBuf::from("sandbox.py"))
            });

        Self {
            mode,
            sandbox_script,
        }
    }

    pub fn mode(&self) -> CodeAgentMode {
        self.mode
    }

    pub fn set_mode(&mut self, mode: CodeAgentMode) {
        self.mode = mode;
    }

    /// Generate task-aware Python code.
    ///
    /// The generator analyses simple keywords in the task description and
    /// emits a complete, runnable script that includes:
    /// - proper structure (main, helpers)
    /// - logging / print statements that document intent
    /// - realistic stubs for common ML / data / IO patterns
    /// - safe-by-default code that will pass the sandbox
    ///
    /// In a production deployment this method can be swapped for a call to a
    /// real OpenCode Go/Zen endpoint without changing any call sites.
    pub async fn generate_python(&self, task: &str) -> Result<String, ConciergeError> {
        info!(mode = ?self.mode, task = %task, "Generating Python code");

        let lower = task.to_lowercase();
        let task_comment = task
            .lines()
            .map(|l| format!("# {}", l))
            .collect::<Vec<_>>()
            .join("\n");

        let body = if lower.contains("train")
            || lower.contains("fine-tune")
            || lower.contains("finetune")
            || lower.contains("lora")
        {
            self.generate_training_scaffold()
        } else if lower.contains("dataset")
            || lower.contains("load data")
            || lower.contains("csv")
            || lower.contains("jsonl")
        {
            self.generate_data_scaffold()
        } else if lower.contains("plugin")
            || lower.contains("custom node")
            || lower.contains("extension")
        {
            self.generate_plugin_scaffold()
        } else if lower.contains("merge") || lower.contains("combine model") {
            self.generate_merge_scaffold()
        } else if lower.contains("infer")
            || lower.contains("predict")
            || lower.contains("generate text")
            || lower.contains("chat")
        {
            self.generate_inference_scaffold()
        } else {
            self.generate_generic_scaffold()
        };

        let header = match self.mode {
            CodeAgentMode::Go => {
                "# Auto-generated by OmniForge Concierge (OpenCode Go style)\n# Mode: lightweight / fast\n"
            }
            CodeAgentMode::Zen => {
                "# Auto-generated by OmniForge Concierge (OpenCode Zen style)\n# Mode: deep / ML-aware\n"
            }
        };

        let code = format!(
            r#"{header}{task_comment}

from typing import Any, Dict, List, Optional
import json

{body}

if __name__ == "__main__":
    result = main()
    print(json.dumps(result, indent=2, default=str))
"#
        );

        Ok(code)
    }

    /// Execute previously generated (or user-supplied) Python code inside the
    /// restricted sandbox.  **Fails hard** if the sandbox script cannot be
    /// located – there is intentionally no unsafe fallback.
    pub async fn execute_sandboxed(&self, code: &str) -> Result<String, ConciergeError> {
        if !self.sandbox_script.exists() {
            return Err(ConciergeError::Sandbox(format!(
                "Sandbox script not found at '{}'. Set CONCIERGE_SANDBOX or place sandbox.py correctly. \
                 Refusing to execute code without the restricted environment.",
                self.sandbox_script.display()
            )));
        }

        let tmp_dir = std::env::temp_dir().join("concierge_sandbox");
        fs::create_dir_all(&tmp_dir)
            .await
            .map_err(|e| ConciergeError::Sandbox(format!("Cannot create temp dir: {e}")))?;

        let code_file = tmp_dir.join(format!("user_code_{}.py", uuid::Uuid::new_v4()));
        fs::write(&code_file, code)
            .await
            .map_err(|e| ConciergeError::Sandbox(format!("Cannot write code file: {e}")))?;

        let sandbox_path = self.sandbox_script.clone();
        let code_path = code_file.clone();

        let output = tokio::task::spawn_blocking(move || {
            Command::new("python3")
                .arg(&sandbox_path)
                .arg(&code_path)
                .output()
        })
        .await
        .map_err(|e| ConciergeError::Sandbox(format!("Join error: {e}")))?
        .map_err(|e| ConciergeError::Sandbox(format!("Sandbox process error: {e}")))?;

        // Clean up
        let _ = fs::remove_file(&code_file).await;

        if output.status.success() {
            Ok(String::from_utf8_lossy(&output.stdout).to_string())
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let stdout = String::from_utf8_lossy(&output.stdout);
            Err(ConciergeError::Sandbox(format!(
                "Sandbox exited non-zero.\nstdout:\n{}\nstderr:\n{}",
                stdout, stderr
            )))
        }
    }

    // ── Scaffold generators ─────────────────────────────────────────────

    fn generate_training_scaffold(&self) -> String {
        r#"
def prepare_dataset(path: str) -> List[Dict[str, Any]]:
    """Load a simple JSONL dataset. Extend for CSV / HuggingFace datasets."""
    print(f"[train] Loading dataset from {path}")
    # In a real run you would open the file; kept sandbox-safe.
    return [{"text": "example", "label": 0}]

def build_lora_config(rank: int = 8, alpha: int = 16) -> Dict[str, Any]:
    return {
        "r": rank,
        "lora_alpha": alpha,
        "target_modules": ["q_proj", "v_proj"],
        "lora_dropout": 0.05,
        "bias": "none",
        "task_type": "CAUSAL_LM",
    }

def train_loop(base_model: str, dataset: List[Dict[str, Any]], config: Dict[str, Any]) -> Dict[str, Any]:
    """Simulate a short training loop. Replace body with real PEFT / transformers code."""
    print(f"[train] Base model: {base_model}")
    print(f"[train] Dataset size: {len(dataset)}")
    print(f"[train] LoRA config: {config}")
    # Placeholder metrics
    metrics = {"loss": 0.42, "epoch": 1, "steps": 100}
    print(f"[train] Finished – metrics: {metrics}")
    return {
        "status": "ok",
        "adapter_path": "/tmp/mock_adapter",
        "metrics": metrics,
    }

def main() -> Dict[str, Any]:
    dataset = prepare_dataset("data/train.jsonl")
    config = build_lora_config()
    return train_loop("base-model-id", dataset, config)
"#
        .to_string()
    }

    fn generate_data_scaffold(&self) -> String {
        r#"
def load_jsonl(path: str) -> List[Dict[str, Any]]:
    print(f"[data] Would load JSONL from {path}")
    return [{"id": 0, "text": "sample"}]

def validate_records(records: List[Dict[str, Any]]) -> Dict[str, Any]:
    n = len(records)
    print(f"[data] Validated {n} records")
    return {"count": n, "ok": True}

def main() -> Dict[str, Any]:
    records = load_jsonl("data/source.jsonl")
    stats = validate_records(records)
    return {"status": "ok", "stats": stats}
"#
        .to_string()
    }

    fn generate_plugin_scaffold(&self) -> String {
        r#"
class ConciergePlugin:
    """Skeleton for a custom OmniForge node / plugin."""

    def __init__(self, name: str = "custom_plugin"):
        self.name = name
        self.config: Dict[str, Any] = {}

    def setup(self, config: Dict[str, Any]) -> None:
        self.config = config
        print(f"[plugin] {self.name} setup with {config}")

    def process(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
        print(f"[plugin] {self.name} processing {list(inputs.keys())}")
        return {"output": inputs.get("input", None), "plugin": self.name}

def main() -> Dict[str, Any]:
    plugin = ConciergePlugin("generated_plugin")
    plugin.setup({"version": "0.1.0"})
    result = plugin.process({"input": "hello"})
    return {"status": "ok", "result": result}
"#
        .to_string()
    }

    fn generate_merge_scaffold(&self) -> String {
        r#"
def linear_merge(weights: List[float], model_ids: List[str]) -> Dict[str, Any]:
    if len(weights) != len(model_ids):
        raise ValueError("weights and model_ids length mismatch")
    print(f"[merge] Linear merge of {model_ids} with weights {weights}")
    return {
        "strategy": "linear",
        "models": model_ids,
        "weights": weights,
        "output": "merged-model-mock",
    }

def main() -> Dict[str, Any]:
    return linear_merge([0.5, 0.5], ["model-a", "model-b"])
"#
        .to_string()
    }

    fn generate_inference_scaffold(&self) -> String {
        r#"
def run_inference(model_id: str, prompt: str, max_tokens: int = 128) -> Dict[str, Any]:
    print(f"[infer] model={model_id} prompt={prompt[:60]}... max_tokens={max_tokens}")
    # Sandbox-safe mock response
    return {
        "model": model_id,
        "prompt": prompt,
        "completion": "[mock completion – replace with real model call]",
        "tokens": 32,
    }

def main() -> Dict[str, Any]:
    return run_inference("local-model", "Explain quantum entanglement in one sentence.")
"#
        .to_string()
    }

    fn generate_generic_scaffold(&self) -> String {
        r#"
def main() -> Dict[str, Any]:
    """Generic entry point generated for an arbitrary task."""
    print("[generic] Task scaffold ready. Replace this body with domain logic.")
    return {
        "status": "ok",
        "mode": "generic",
        "note": "Edit main() to implement the requested behaviour.",
    }
"#
        .to_string()
    }
}
