// Proves `PythonBridge::train_step` is real end-to-end training, not just
// plumbing that compiles: trains a single `y = x * w` op against a target
// generated by a known true weight, and checks the loss actually decreases
// and the learned weight moves toward the true one. Ignored by default
// (needs `torch` importable) — run with `cargo test -- --ignored`.
use brainbuilder_core::component::descriptor::DataType;
use brainbuilder_core::interop::python::PythonBridge;
use brainbuilder_core::interop::arena::SharedArena;
use brainbuilder_core::runtime::cpu_backend::CpuDevice;
use brainbuilder_core::runtime::device::Device;
use brainbuilder_core::runtime::scheduler::ExecutableOp;
use std::collections::HashMap;
use std::sync::Arc;

fn tensor_from(values: &[f32]) -> brainbuilder_core::Tensor {
    let device = CpuDevice;
    let t = device.alloc(&[values.len()], DataType::Float32);
    unsafe {
        let dst = (*t.0).dl_tensor.data as *mut f32;
        std::ptr::copy_nonoverlapping(values.as_ptr(), dst, values.len());
    }
    t
}

fn read(tensor: &brainbuilder_core::Tensor, len: usize) -> Vec<f32> {
    unsafe { std::slice::from_raw_parts((*tensor.0).dl_tensor.data as *const f32, len).to_vec() }
}

#[test]
#[ignore]
fn training_loop_actually_reduces_loss_and_learns_the_true_weight() {
    let fixtures_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    std::env::set_var("PYTHONPATH", &fixtures_dir);

    let bridge = PythonBridge::new(Arc::new(SharedArena::new())).unwrap();

    let x_values = [1.0f32, 2.0, 3.0, 4.0];
    let true_w = 3.0f32;
    let target_values: Vec<f32> = x_values.iter().map(|x| x * true_w).collect();

    let x = tensor_from(&x_values);
    let target = tensor_from(&target_values);
    // Start far from the true weight (3.0) so learning is unmistakable.
    let mut w = tensor_from(&[0.1, 0.1, 0.1, 0.1]);

    let ops = vec![ExecutableOp {
        node_id: "n1".into(),
        component: "bb_scale_component".into(),
        language: "python".into(),
        entry: "forward".into(),
        inputs: vec!["x".into(), "w".into()],
        outputs: vec!["y".into()],
        param_inputs: vec!["w".into()],
        trainable_inputs: vec!["w".into()],
        zero_init_inputs: vec![],
        hyperparams: serde_json::json!({}),
        resolved_param_shapes: Default::default(),
    }];

    let mut losses = Vec::new();
    for _ in 0..200 {
        let mut inputs = HashMap::new();
        inputs.insert("x".to_string(), x.clone());
        inputs.insert("w".to_string(), w.clone());

        let (loss, updated) = bridge
            .train_step(&ops, inputs, "y", &target, "mse", "sgd", 0.05, &["w".to_string()])
            .expect("train_step failed");

        losses.push(loss);
        w = updated.get("w").expect("w not returned").clone();
    }

    let first_loss = losses[0];
    let last_loss = *losses.last().unwrap();
    assert!(
        last_loss < first_loss * 0.01,
        "expected loss to collapse over 200 steps: first={first_loss}, last={last_loss}"
    );

    let learned_w = read(&w, 4);
    for w_i in learned_w {
        assert!(
            (w_i - true_w).abs() < 0.05,
            "expected learned weight ~{true_w}, got {w_i}"
        );
    }
}
